In [15]:
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)
print(a.ndim)

[1, 2, 3, 4, 5, 6]


AttributeError: 'list' object has no attribute 'ndim'

In [7]:
[1, 2, 3, 4, 5, 6]  

[[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]]


In [7]:
a=[1,2,3]
b=[4,5,6]


result=[]
for i,j in zip(a,b):
    
    result.append(i+j)
print(result)

[5, 7, 9]


In [1]:
import numpy as np


In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])


c=np.array([7,8,9])
d=a+b+c
print(d)
print(a.ndim)


[12 15 18]
1


In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
a.shape

(3,)

In [10]:
a.size

3

In [18]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [20]:
b.shape # row,column

(2, 3)

In [21]:
b.size

6

In [23]:
b.dtype

dtype('int32')

In [25]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [26]:
c.shape

(2, 2, 3)

In [27]:
c.size

12

In [14]:
weight=np.array([40,54,64,35,56])
height=np.array([1.78,1.68,1.8,2.0,1.67])
BMI=weight/height**2
print(BMI)

[12.6246686  19.13265306 19.75308642  8.75       20.07960128]


In [5]:
weight=np.array([40,54,64,35,56])
print(weight)

[40 54 64 35 56]


In [10]:
weight[0]

40

In [11]:
weight[4]

56

In [12]:
weight[-1]

56

In [13]:
weight[1:4]

array([54, 64, 35])

In [6]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [7]:
x[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
x[0,1]

2

In [12]:
print(x[:,0])

[1 4]


In [10]:
x[,0]

SyntaxError: invalid syntax (<ipython-input-10-ba4069a422b8>, line 1)

In [4]:
x[:,0:2]

NameError: name 'x' is not defined

In [5]:
y=np.arange(40).reshape(5,8)
print(y)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [39]:
y[0:2,]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [42]:
y[0:2,0:2]

array([[0, 1],
       [8, 9]])

In [44]:
y[1:4,2:5]

array([[10, 11, 12],
       [18, 19, 20],
       [26, 27, 28]])

In [ ]:
y[,]

In [14]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [17]:
data=np.arange(1,101).reshape(10,10)
print(data)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [23]:
print(data.T)

[[  1  11  21  31  41  51  61  71  81  91]
 [  2  12  22  32  42  52  62  72  82  92]
 [  3  13  23  33  43  53  63  73  83  93]
 [  4  14  24  34  44  54  64  74  84  94]
 [  5  15  25  35  45  55  65  75  85  95]
 [  6  16  26  36  46  56  66  76  86  96]
 [  7  17  27  37  47  57  67  77  87  97]
 [  8  18  28  38  48  58  68  78  88  98]
 [  9  19  29  39  49  59  69  79  89  99]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [27]:
data.diag()

AttributeError: 'numpy.ndarray' object has no attribute 'diag'

In [34]:
val=np.arange(1,26).reshape(5,5)
val_1=np.sqrt(val)
print('value of val =\n {}\n and value of sqrt val or val_1=\n{} '.format(val,val_1))

value of val =
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 and value of sqrt val or val_1=
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]
 [4.         4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.        ]] 


In [37]:
val_2=10*val
print(val_2)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]


In [39]:
val_3=val**2
print(val_3)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]]


In [46]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0.])

In [51]:
one=np.ones(5)
print(one)

[1. 1. 1. 1. 1.]


In [52]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
one=np.ones((4,5))
three=one*3
print(three)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [56]:
three_transpose=three.T
print(three_transpose)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [52]:
z=np.arange(1,26).reshape(5,5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [53]:
print('shape of thie z matrix is = {} \n and dimension of this matrix is = {} \n and size of this matrix is = {}'.format(z.shape,z.ndim,z.size))

shape of thie z matrix is = (5, 5) 
 and dimension of this matrix is = 2 
 and size of this matrix is = 25


In [55]:
z[1::3,]

array([[ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])

In [4]:
x.shape

(2, 3)

In [5]:
x.dtype

dtype('int32')

In [7]:
x[0,1]# here 1st value define row and second value columns  

2

In [2]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [16]:
x.shape

(1, 3, 3)

In [4]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('value of x is = \n',x)
print('shape of the x matrix is = ',x.shape)

value of x is = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of the x matrix is =  (3, 3)


In [20]:
x[1,1]

5

In [ ]:
a=np.arrray([])

### slicing

In [21]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
x[:,1]


array([2, 5, 8])

In [23]:
x[:,2]

array([3, 6, 9])

In [13]:
print('1st column of x variable is:',x[:,0])
print('x is\n',x)

1st column of x variable is: [1 4]
x is
 [[1 2 3]
 [4 5 6]]


In [14]:
y=x[:,1]
y.shape

(2,)

### transpose the matrixusing  .T


In [15]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
y=x.T
y


array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
x.shape

(2, 3)

In [21]:
y.shape

(3, 2)

In [22]:
x.data

In [23]:
x.dtype

dtype('int32')

In [24]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [26]:
x.size

9

In [24]:
x.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
x.size

6

In [31]:
z=np.array([[100,200,400,3],[50,4,6,5]])

In [33]:
z.size  #it rerpresent number of element of the array


8

In [35]:
x.itemsize#length  of one array element in bytes

4

In [36]:
x.nbytes

24

In [37]:
z.nbytes

32

In [38]:
z.itemsize

4

In [39]:
z.ndim

2

In [40]:
x=np.arange(1,7)
print(x)

[1 2 3 4 5 6]


### reshape

In [52]:
x=x.reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

### using flat

#### flat conver 1D 

In [53]:
x.flat[2]

3

In [54]:

x.flat[5]

6

In [55]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
type(x.T.flat[2])

numpy.int32

In [60]:
type(x.flat)

numpy.flatiter

In [66]:
x=np.zeros((3,5,2),dtype=np.complex128)
print(x)

[[[0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j]]]


### .ndim (number of array dimension )

In [67]:
x.ndim

3

In [70]:
x=np.array([[1,2,3,4]])

In [71]:
print(x.shape)

(1, 4)


In [73]:
a=np.zeros((2,3,4))

In [74]:
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [75]:
print(a.shape)

(2, 3, 4)


In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [6]:
np.dot(a,b)

32

In [58]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,12,13],[14,15,16]])

print(a)
print()
print(b)
print()
print(a+b)

[[1 2 3]
 [4 5 6]]

[[11 12 13]
 [14 15 16]]

[[12 14 16]
 [18 20 22]]


In [59]:
print(b-a)

[[10 10 10]
 [10 10 10]]


In [61]:
print(a*b)

array([[11, 24, 39],
       [56, 75, 96]])

In [62]:
print(a)

[[1 2 3]
 [4 5 6]]


In [63]:
np.sum(a)

21

In [64]:
np.sum(a,axis=0)

array([5, 7, 9])

In [65]:
np.sum(a,axis=1)

array([ 6, 15])

In [89]:
import numpy as np
import time
start=time.time()
a=np.sum(np.arange(10000))

end=time.time()
print(a)
print()
print('vectorized '+ str((end-start)*1000) +'ms')

49995000

vectorized 0.0ms


In [90]:
import numpy as np
import time
start=time.time()
total=0
for i in range(10000):
    total=i+total
print(total)    

end=time.time()

print()
print('non-vectorized  '+ str((end-start)*1000) +'ms')

49995000

non-vectorized  3.9992332458496094ms


In [41]:
print('non vectrized is faster than' +str( 271.99840545654297/3.997325897216797)+ 'time')

non vectrized is faster than68.04509125611357time


In [67]:
np.sum(np.arange(10000))

49995000

In [68]:
total=0
for  i in range(10000):
    total=total+i
print(total)    

49995000


In [92]:
a=np.arange(1,101).reshape(10,10)
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [93]:
np.sum(a)

5050

In [94]:
np.sum(a,axis=0)

array([460, 470, 480, 490, 500, 510, 520, 530, 540, 550])

In [97]:
print(np.sum(a,axis=1,keepdims=True))

[[ 55]
 [155]
 [255]
 [355]
 [455]
 [555]
 [655]
 [755]
 [855]
 [955]]


In [98]:
a=np.array([1,2,3,4,5])
b=np.array([11,22,33,44,55])
c=np.dot(a,b)
print(c)

605


In [1]:
import numpy as np


In [4]:
a=np.array([-1,2,-3,4])
print(a)

[-1  2 -3  4]


In [7]:
b=np.abs(a)

In [8]:
np.sqrt(b)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [9]:
np.sin(a)

array([-0.84147098,  0.90929743, -0.14112001, -0.7568025 ])

In [10]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [21]:
np.tan(b)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [13]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [14]:
np.exp(a)

array([3.67879441e-01, 7.38905610e+00, 4.97870684e-02, 5.45981500e+01])

In [17]:
def sigmoid(z):
    a=1/(1+np.exp(-z))
    return a

In [19]:
sigmoid(a)

array([0.26894142, 0.88079708, 0.04742587, 0.98201379])

In [22]:
a=np.arange(9).reshape(3,3)
b=np.arange(11,20).reshape(3,3)
print(a)
print()
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [23]:
print(np.multiply(a,b))

[[  0  12  26]
 [ 42  60  80]
 [102 126 152]]


In [24]:
print(np.divide(a,b))

[[0.         0.08333333 0.15384615]
 [0.21428571 0.26666667 0.3125    ]
 [0.35294118 0.38888889 0.42105263]]


In [26]:
print(np.subtract(a,b))

[[-11 -11 -11]
 [-11 -11 -11]
 [-11 -11 -11]]


In [27]:
print(np.add(a,b))

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [28]:
print(np.power(a,b))

[[          0           1        8192]
 [    4782969  1073741824 -2030932031]
 [  193331200 -1777531471           0]]


In [32]:
print(np.maximum(a,b))

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [33]:
print(np.minimum(a,b))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1]:
import numpy as np


In [2]:
a=np.arange(1,101).reshape(10,10)
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [3]:
np.mean(a)

50.5

In [6]:
np.mean(a,axis=0)

array([46., 47., 48., 49., 50., 51., 52., 53., 54., 55.])

In [8]:
np.mean(a,axis=1,keepdims=True)

array([[ 5.5],
       [15.5],
       [25.5],
       [35.5],
       [45.5],
       [55.5],
       [65.5],
       [75.5],
       [85.5],
       [95.5]])

In [4]:
np.max(a)

100

In [10]:
np.max(a,axis=0,keepdims=True)

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [11]:
np.max(a,axis=1,keepdims=True)

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [5]:
np.min(a)

1

In [13]:
np.mean(a,axis=0)

array([46., 47., 48., 49., 50., 51., 52., 53., 54., 55.])

In [14]:
np.mean(a,axis=1,keepdims=True)

array([[ 5.5],
       [15.5],
       [25.5],
       [35.5],
       [45.5],
       [55.5],
       [65.5],
       [75.5],
       [85.5],
       [95.5]])

In [15]:
np.std(a)

28.86607004772212

In [16]:
np.std(a,axis=0)

array([28.72281323, 28.72281323, 28.72281323, 28.72281323, 28.72281323,
       28.72281323, 28.72281323, 28.72281323, 28.72281323, 28.72281323])

In [17]:
np.std(a,axis=1,keepdims=True)

array([[2.87228132],
       [2.87228132],
       [2.87228132],
       [2.87228132],
       [2.87228132],
       [2.87228132],
       [2.87228132],
       [2.87228132],
       [2.87228132],
       [2.87228132]])

In [18]:
np.argmax(a)

99

In [20]:
print(np.argmax(a,axis=0))

[9 9 9 9 9 9 9 9 9 9]


In [24]:
print(np.argmin(a,axis=1))

[0 0 0 0 0 0 0 0 0 0]


In [1]:
import numpy as np 
a=np.array([2,3,5,8,9])

In [10]:
a[0]=12.43
print(a)
a.dtype

[12  3  5  8  9]


dtype('int32')

In [6]:
b=np.array([1.2,3.5,6.7])
print(b)

[1.2 3.5 6.7]


In [7]:
b[0]=5
print(b)

[5.  3.5 6.7]


In [11]:
b.dtype

dtype('float64')

In [12]:
a=np.array([1,2,3,4.5,6.7])
print(a)

[1.  2.  3.  4.5 6.7]


In [14]:
a=np.array([1,2,3,4,5,6])
a[0:2]

array([1, 2])

In [15]:
y=np.arange(40).reshape(5,8)
print(y)


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [16]:
y[0::2,::]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [17]:
y[::,0::2]

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

In [22]:
y[2:6:2,3:6:2]

array([[19, 21],
       [35, 37]])

In [2]:
import numpy as np
np.random.randint(100)

11

In [4]:
np.random.randint(100,size=(5))

array([38, 10, 88, 12, 58])

In [6]:
np.random.randint(1000,size=(5,5))

array([[129, 780, 369, 221, 338],
       [ 90, 405, 293,  41, 956],
       [454, 936, 537, 746,  26],
       [112, 564, 313,   8, 725],
       [ 94,   4, 935, 291, 170]])

In [8]:
np.random.rand()

0.1119168473596941

In [9]:
np.random.rand(5)

array([0.5170189 , 0.70738658, 0.22796899, 0.23154111, 0.69031338])

In [12]:
np.random.rand(5,5)

array([[7.49367264e-01, 1.07330900e-01, 7.60972449e-01, 2.69975978e-01,
        3.13136873e-01],
       [7.33186260e-01, 9.80332446e-01, 6.15748140e-01, 1.16992739e-01,
        9.27901035e-02],
       [3.07526637e-01, 3.07938821e-01, 7.97501944e-01, 8.61390679e-02,
        1.72328746e-01],
       [6.40486514e-01, 6.64454913e-01, 2.53075869e-02, 7.01820136e-01,
        3.08467435e-01],
       [1.27336812e-01, 6.10926522e-04, 7.17718790e-01, 9.90647983e-01,
        1.14461646e-02]])

In [14]:
np.random.choice([1,2,3,4,5])

5

In [16]:
np.random.choice([1,3,9,6,4],size=(3,4))

array([[4, 4, 3, 1],
       [4, 4, 1, 3],
       [6, 6, 9, 1]])

In [7]:
a=[1,2,3,4,5]
b=a


In [8]:
print(a)

[1, 2, 3, 4, 5]


In [9]:
print(b)

[1, 2, 3, 4, 5]


In [10]:
a[2]=15

In [15]:
a=b

In [16]:
a is b

True